# Generated by Django 5.1.3 on 2024-11-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='acta_de_nacimiento',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='numero_celular',
            new_name='salario',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='curp',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='rfc',
        ),
    ]
